version: "3.8"

services:
  nginx:
    image: sweetbubalexxx/moneyger-front:v1.1.0
    depends_on:
      - api
    networks:
      - default
      - notifications_service_network
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files:/app/staticfiles

  api:
    image: sweetbubalexxx/moneyger-server:v2.0.0
    depends_on:
      - db
      - redis
      - rabbitmq
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: postgres://django:${POSTGRES_PASSWORD}@db:5432/django
      CACHE_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/1
      CELERY_RESULT_BACKEND: redis://:${REDIS_PASSWORD}@redis:6379/2
      WEBSOCKET_CHANNEL_LAYERS: redis://:${REDIS_PASSWORD}@redis:6379/3
      RABBITMQ_URL: amqp://${RABBITMQ_USER:?}:${RABBITMQ_PASSWORD:?}@rabbitmq:5672/%2F
      EMAIL_URL: ${EMAIL_URL:-filemail:////tmp/mail/}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-}
      XFF_TRUSTED_PROXY_DEPTH: ${XFF_TRUSTED_PROXY_DEPTH:-1}

  celery_worker:
    extends:
      service: api
    depends_on:
      - db
      - redis
      - rabbitmq
    command: celery -A moneymanager worker --autoscale 2,1 --loglevel INFO --events

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 5432
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --loglevel notice --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    expose:
      - 6379

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:?}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:?}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 536870912
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - default
      - notifications_service_network
    expose:
      - 5672
      - 15672

volumes:
  database_data:
  rabbitmq_data:
  static_files:

networks:
  notifications_service_network:
    name: ${NOTIFICATIONS_SERVICE_NETWORK:-moneyger-notifications}
    external: ${NOTIFICATIONS_SERVICE_NETWORK_EXTERNAL:-false}

